### ISSUE TITLE
Sticker Error [ Repl.it ]

### ISSUE THREAD

**Issue by yourantithesis** [4relial/megumi-md#4]
using WA v2.2243.7, isLatest: true
Connection Status:  connecting
Connection Status:  open
30/11/2022|16:18:50>>>>  Error: ENOENT: no such file or directory, open './assets/downloads/2idzd.jpeg'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at Object.downloadMedia (/home/runner/megumi-md/lib/index.js:338:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.main (/home/runner/megumi-md/lib/controller.js:273:19)
    at async exports.core (/home/runner/megumi-md/lib/index.js:1408:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './assets/downloads/2idzd.jpeg'
} <<<<

**Comment by 4relial** [comment]
You can make folder named "downloads" in assets folder to fix it
